### ISSUE TITLE
Уточнить в README.md касательно версии NodeJS.

### ISSUE THREAD

**Issue by theart84** [netology-code/bjs-diplom#20]
@vovachebr 

Проблема:
Есть подозрение,что у людей, которые ставят версию current бывают ошибки при старте сервера.

Добавить уточнение:
В котором написать, что нужно ставить LTS версию.
Здесь:
>1. Установите NodeJS для своей операционной системы. Если NodeJS уже был установлен ранее, обновите его до последней версии.

**Comment by vovachebr** [comment]
https://github.com/netology-code/bjs-diplom/commit/05a454b922bbbab9d9b85a5865aaaae11501fd69
